### Register
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name" : "and",
    "email" : "and@gmail.com",
    "password":"and123",
    "confirmPassword": "and123"
}

### Login 
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email" : "kaca2@gmail.com",
    "password" : "kaca123"
}

### Get data
GET http://localhost:5000/api/users/
Content-Type: application/json
Authorization: Bearer 

### Update Data
PATCH  http://localhost:5000/api/users/
Content-Type: application/json

{
    "email" : "kaca2@gmail.com"
}

### Refresh Token , Tidak Perlu Login
GET http://localhost:5000/token

### Logout
DELETE http://localhost:5000/api/users/logout 






